[package]
name = "cadconvert-algo"
version = "0.1.0"
edition = "2021"

[dependencies]
cadconvert-core = { path = "../cadconvert-core" }
anyhow.workspace = true
thiserror.workspace = true
nalgebra = "0.32"
itertools = "0.12"
chrono = "0.4"
